# Site settings
title:              "Ozzie's Blog"
email:              ztianjin@me.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog, focus on computer science 
baseurl:            ""
url:                "https://ozzie00.github.io"
facebook : ozzie00
twitter_username:   __Ozzie_
github_username:    ozzie00

future:             True
timezone:           China/Beijing

# Build settings
markdown:           kramdown
gems:               [jekyll-paginate]
paginate:           15
