# Site settings
title:              "Ozzie's Sky"
email:              ztianjin@onemee.net
description: > # this means to ignore newlines until "baseurl:"
  This is my blog, most of which are about one of two major themes. The first is computer
  science, which is my area of specialty as an software engineer. The
  second can be broadly categorized as "Others," which relates to my
  experience and knowledge in other fields.
baseurl:            ""
url:                "https://ozzie00.github.io"
twitter_username:   @__Ozzie_
github_username:    ozzie00
future:             True
timezone:           China/Beijing

# Build settings
markdown:           kramdown
gems:               [jekyll-paginate]
paginate:           15
